import array as arr
fruit_counts = arr.array('i', [3, 5, 2, 4])
print("Fruit counts array:", fruit_counts)
fruit_counts.insert(0, 1)
fruit_counts.append(6)
print("Fruit counts after adding items:", fruit_counts)
count_of_4 = fruit_counts.count(4)
print("Number of times 4 appears:", count_of_4)
fruit_counts.reverse()
print("Reversed Fruit counts array :", fruit_counts)